/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemavendas.dashboard;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author rhuan
 */
public class ViewDashBoard extends javax.swing.JFrame {

    
    private List<PanelDashboard> panels;
    
    /**
     * Creates new form ViewDashBoard
     */
    public ViewDashBoard() {
        initComponents();
        getContentPane().setLayout(new java.awt.GridLayout(2, 3, 5, 5));
        
        panels = new ArrayList();
        setSize(1108, 660);
        

        PanelDashboard a4 = new PanelDashboard(10);
        addPanel(a4);
        PanelDashboard a5 = new PanelDashboard(10);
        addPanel(a5);
        
        
        
        PanelCliente c1 = new PanelCliente(1);
        addPanel(c1);
        
        PanelProduto c2 = new PanelProduto(2);
        addPanel(c2);
        
        PanelEstoque c3 = new PanelEstoque(3);
        addPanel(c3);
        
        PanelVendas c4 = new PanelVendas(4);
        addPanel(c4);
        
    }

    //[153,255,255]
    //[102,204,255]
    //[102,102,255]

    
    public void setPanels(List<PanelDashboard> panels) {
        this.panels = panels;
    }

    public List<PanelDashboard> getPanels() {
        return panels;
    }
    
    public PanelDashboard getPanel(int codigo) {
        for (PanelDashboard panel : panels) {
            if (panel.getCodigo() == codigo) {
                return panel;
            }
        }
        return null;
    }
    
    public void addPanel(PanelDashboard panel) {
        this.panels.add(panel);
        add(panel);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(3, 3, 5, 5));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
