/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemavendas.visualizacao;

import infra.comunicacao.Erro;
import infra.comunicacao.Sucess;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import sistemavendas.controle.CEstoque;
import sistemavendas.controle.CProduto;
import sistemavendas.negocio.NProduto;

/**
 *
 * @author rhuan
 */
public class ViewExclusaoProdutos extends javax.swing.JFrame {

//    MyTableModel model = new MyTableModel();
    
    
    /**
     * Creates new form ViewExclusaoProdutos
     */
    public ViewExclusaoProdutos() {
        initComponents();
        
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        
        //id
        jTableExclusaoProdutos.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableExclusaoProdutos.getColumnModel().getColumn(0).setMaxWidth(40);
        //codigo
        jTableExclusaoProdutos.getColumnModel().getColumn(1).setPreferredWidth(45);
        jTableExclusaoProdutos.getColumnModel().getColumn(1).setMaxWidth(45);
        // nome
        jTableExclusaoProdutos.getColumnModel().getColumn(2).setPreferredWidth(150);
        // codigo barras
        jTableExclusaoProdutos.getColumnModel().getColumn(3).setPreferredWidth(150);
        //excluir
        jTableExclusaoProdutos.getColumnModel().getColumn(4).setPreferredWidth(45);
        jTableExclusaoProdutos.getColumnModel().getColumn(4).setMaxWidth(45);
        
        
        btExcluir.addActionListener((ActionEvent e) -> {
            
            List<NProduto> produtos = getProdutosSelecionados();
            if (!produtos.isEmpty()) {
                CProduto controller = new CProduto();
                
                
                for (NProduto p : produtos) {
                    System.out.println(p.toString());
                    try {
                        controller.excluir(p);
                        System.out.println("excluir " + p);
                        
                    } catch (Erro e2) {
                        new Erro("Falha ao excluir registro : " + p.getNome(), "").show();                       
                    }
                }
                new Sucess("Registros excluidos com sucesso!", "").show();
                
                
                try {
                    // Atualizar quantidade de produtos
                    NProduto temp = controller.buscarPorId(produtos.get(0).getId());
                    CEstoque controllerEstoque = new CEstoque();
                    controllerEstoque.retirar(temp, produtos.size());
                    
                    // atualiza o ultimo codigo de barras
                    Integer cb = controller.recuperarUltimoCodigoBarras(temp);
                    
                    temp.setCodigoBarras(cb);
                    controller.alterar(temp);
                } catch (Erro ex) {
                    Logger.getLogger(ViewExclusaoProdutos.class.getName()).log(Level.SEVERE, null, ex);
                }
                               
                DefaultTableModel model = (DefaultTableModel) jTableExclusaoProdutos.getModel();
                model.setNumRows(0);
            }
        });        
    }

    
    
    
    
    
    public void adicionarProdutos(List<NProduto> lista) {
        try {
            
            DefaultTableModel model = (DefaultTableModel) jTableExclusaoProdutos.getModel();
            jTableExclusaoProdutos.setModel(model);

            lista.stream().forEach((nProduto) -> {
                model.addRow(new Object[] {
                    nProduto.getId(),
                    nProduto.getCodigo(),
                    nProduto.getNome(),
                    nProduto.getCodigoBarras(),
                    false
                });
            });

        } catch (Exception e) {}
    }
    
    
    public List<NProduto> getProdutosSelecionados() {
        List<NProduto> ps = new ArrayList();
        for (int i = 0; i < jTableExclusaoProdutos.getRowCount(); i++) {
            boolean excluir = (boolean) jTableExclusaoProdutos.getValueAt(i, 4);
            if (excluir) {
                NProduto p = new NProduto();
                p.setId((Integer) jTableExclusaoProdutos.getValueAt(i, 0));
                p.setCodigoBarras((Integer) jTableExclusaoProdutos.getValueAt(i, 3));
                ps.add(p);
            }
        }
        return ps;
    }
    

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExclusaoProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 246, 250));

        btExcluir.setText("Excluir");

        jTableExclusaoProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Código", "Nome", "Código Barras", "Excluir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableExclusaoProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableExclusaoProdutos;
    // End of variables declaration//GEN-END:variables



}
