/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemavendas.visualizacao;

import infra.comunicacao.Erro;
import infra.comunicacao.Sucess;
import infra.validadores.ViewValidator;
import java.awt.event.ActionEvent;
import sistemavendas.controle.CUsuario;
import sistemavendas.negocio.NUsuario;

/**
 *
 * @author rhuan
 */
public class ViewRedefinirSenha extends javax.swing.JFrame {

    /**
     * Creates new form ViewRedefinirSenha
     */
    public ViewRedefinirSenha() {
        initComponents();
        initViewValidator();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null); 
        
        
        btSalvar.addActionListener((ActionEvent e) -> {
            cadastrarNovaSenha();
        });
        
        Character echo = fSenha.getEchoChar();
        fMostraSenha.addActionListener((ActionEvent e ) -> {
            
            if (fMostraSenha.isSelected()) {
                fSenha.setEchoChar((char)0);
                fConfirmaSenha.setEchoChar((char)0);
            } else {
                fSenha.setEchoChar(echo);
                fConfirmaSenha.setEchoChar(echo);
            }
            
        });
        
        fNome.setText("Rhuan Pablo");
        fUsuario.setText("rhuan");
        fSenha.setText("123");
        fConfirmaSenha.setText("123");
        fCpf.setText("025 . 335 . 721 - 79");
        fEmail.setText("rhuanpablo13@hotmail.com");
        
        
    }

    
    
    private void cadastrarNovaSenha() {
        String usuario = fUsuario.getText();
        String senha = new String(fSenha.getPassword());
        String confirmaSenha = new String(fConfirmaSenha.getPassword());
        
        if (usuario.equalsIgnoreCase("admin") || senha.equalsIgnoreCase("admin") || confirmaSenha.equalsIgnoreCase("admin")) {
            new Erro("Usuário e Senha não podem ser 'admin'", "Redefinir Senha").show();
            return;
        }
        
        if (!senha.equals(confirmaSenha)) {
            new Erro("Senhas não são iguais, por favor corrija sua senha!", "Redefinir Senha").show();
            return;
        }
        
        if (fNome.getText().isEmpty() || fUsuario.getText().isEmpty() || fSenha.getPassword().length == 0 || fConfirmaSenha.getPassword().length == 0 || fCpf.getText().isEmpty() || fEmail.getText().isEmpty()) {
            new Erro("Verifique se todos os campos estão preenchidos corretamente!", "Redefinir Senha").show();
            return;
        }
        
        
        CUsuario controllerUsuario = new CUsuario();
        NUsuario usuarioTemp = controllerUsuario.recuperarPorUsuario("admin");
        if (usuarioTemp == null) {
            usuarioTemp = new NUsuario();
        }
        
        usuarioTemp.setUsuario(usuario);
        usuarioTemp.setSenha(senha);
        usuarioTemp.setConfirmaSenha(confirmaSenha);
        usuarioTemp.setCpf(fCpf.getText());
        usuarioTemp.setNome(fNome.getText());
        usuarioTemp.setEmail(fEmail.getText());
        usuarioTemp.setCodigo(1);
        usuarioTemp.setAdministrador(true);
        usuarioTemp.setAtivo(true);
        
        try {
            controllerUsuario = new CUsuario();
            if (usuarioTemp.getId() != null) {
                controllerUsuario.alterar(usuarioTemp);
                new Sucess("Usuário administrador redefinido com sucesso!", "Redefinir Senha").show();
            } else {
                controllerUsuario.inserir(usuarioTemp);
                new Sucess("Usuário administrador cadastrado com sucesso!", "Redefinir Senha").show();
            }            
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        } catch (Erro ex) {
            ex.show();
        }
    }
    
    
    private void initViewValidator() {
        ViewValidator validator = new ViewValidator();
        validator.required(fNome);
        validator.required(fUsuario);
        validator.required(fEmail);
        validator.required(fCpf);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelUsuario8 = new javax.swing.JLabel();
        fSenha = new javax.swing.JPasswordField();
        jLabelUsuario9 = new javax.swing.JLabel();
        fConfirmaSenha = new javax.swing.JPasswordField();
        fMostraSenha = new javax.swing.JCheckBox();
        jLabelUsuario1 = new javax.swing.JLabel();
        jLabelTituloCadastro = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        fUsuario = new javax.swing.JTextField();
        jLabelUsuario7 = new javax.swing.JLabel();
        fNome = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        fCpf = new javax.swing.JFormattedTextField();
        jLabelUsuario18 = new javax.swing.JLabel();
        jLabelUsuario11 = new javax.swing.JLabel();
        fEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 246, 250));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 370));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 370));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelUsuario8.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 12)); // NOI18N
        jLabelUsuario8.setForeground(new java.awt.Color(153, 153, 153));
        jLabelUsuario8.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 88, 0, 0);
        jPanel1.add(jLabelUsuario8, gridBagConstraints);

        fSenha.setBackground(new java.awt.Color(245, 246, 250));
        fSenha.setToolTipText("Insira sua nova senha");
        fSenha.setAlignmentX(0.0F);
        fSenha.setAlignmentY(0.0F);
        fSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        fSenha.setMinimumSize(null);
        fSenha.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 88, 0, 0);
        jPanel1.add(fSenha, gridBagConstraints);

        jLabelUsuario9.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 12)); // NOI18N
        jLabelUsuario9.setForeground(new java.awt.Color(153, 153, 153));
        jLabelUsuario9.setText("Confirma Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 88, 0, 0);
        jPanel1.add(jLabelUsuario9, gridBagConstraints);

        fConfirmaSenha.setBackground(new java.awt.Color(245, 246, 250));
        fConfirmaSenha.setToolTipText("Repita a senha");
        fConfirmaSenha.setAlignmentX(0.0F);
        fConfirmaSenha.setAlignmentY(0.0F);
        fConfirmaSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        fConfirmaSenha.setMinimumSize(null);
        fConfirmaSenha.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 88, 0, 0);
        jPanel1.add(fConfirmaSenha, gridBagConstraints);

        fMostraSenha.setBackground(new java.awt.Color(245, 246, 250));
        fMostraSenha.setAlignmentY(0.0F);
        fMostraSenha.setMaximumSize(new java.awt.Dimension(25, 25));
        fMostraSenha.setMinimumSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 7, 0, 0);
        jPanel1.add(fMostraSenha, gridBagConstraints);

        jLabelUsuario1.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 12)); // NOI18N
        jLabelUsuario1.setForeground(new java.awt.Color(153, 153, 153));
        jLabelUsuario1.setText("Mostrar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 7, 0, 0);
        jPanel1.add(jLabelUsuario1, gridBagConstraints);

        jLabelTituloCadastro.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 18)); // NOI18N
        jLabelTituloCadastro.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTituloCadastro.setText("Redefinir Usuário Administrador");
        jLabelTituloCadastro.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 110, 0, 87);
        jPanel1.add(jLabelTituloCadastro, gridBagConstraints);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/30x30/salvar2.png"))); // NOI18N
        btSalvar.setToolTipText("Salvar Registro");
        btSalvar.setAlignmentY(0.0F);
        btSalvar.setMaximumSize(new java.awt.Dimension(80, 39));
        btSalvar.setMinimumSize(new java.awt.Dimension(80, 39));
        btSalvar.setOpaque(false);
        btSalvar.setPreferredSize(new java.awt.Dimension(80, 39));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 72, 13, 87);
        jPanel1.add(btSalvar, gridBagConstraints);

        fUsuario.setBackground(new java.awt.Color(245, 246, 250));
        fUsuario.setAlignmentX(0.0F);
        fUsuario.setAlignmentY(0.0F);
        fUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        fUsuario.setMinimumSize(null);
        fUsuario.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 88, 0, 0);
        jPanel1.add(fUsuario, gridBagConstraints);

        jLabelUsuario7.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 12)); // NOI18N
        jLabelUsuario7.setForeground(new java.awt.Color(153, 153, 153));
        jLabelUsuario7.setText("Usuário");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 88, 0, 0);
        jPanel1.add(jLabelUsuario7, gridBagConstraints);

        fNome.setBackground(new java.awt.Color(245, 246, 250));
        fNome.setAlignmentX(0.0F);
        fNome.setAlignmentY(0.0F);
        fNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        fNome.setMinimumSize(new java.awt.Dimension(400, 20));
        fNome.setName(""); // NOI18N
        fNome.setPreferredSize(new java.awt.Dimension(400, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = -200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 88, 0, 0);
        jPanel1.add(fNome, gridBagConstraints);

        jLabelUsuario.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 12)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jLabelUsuario.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 88, 0, 0);
        jPanel1.add(jLabelUsuario, gridBagConstraints);

        fCpf.setBackground(new java.awt.Color(245, 246, 250));
        fCpf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        try {
            fCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### . ### . ### - ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fCpf.setAlignmentX(0.0F);
        fCpf.setAlignmentY(0.0F);
        fCpf.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 88, 0, 0);
        jPanel1.add(fCpf, gridBagConstraints);

        jLabelUsuario18.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 12)); // NOI18N
        jLabelUsuario18.setForeground(new java.awt.Color(153, 153, 153));
        jLabelUsuario18.setText("CPF");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 88, 0, 0);
        jPanel1.add(jLabelUsuario18, gridBagConstraints);

        jLabelUsuario11.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 12)); // NOI18N
        jLabelUsuario11.setForeground(new java.awt.Color(153, 153, 153));
        jLabelUsuario11.setText("E-mail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 88, 0, 0);
        jPanel1.add(jLabelUsuario11, gridBagConstraints);

        fEmail.setBackground(new java.awt.Color(245, 246, 250));
        fEmail.setAlignmentX(0.0F);
        fEmail.setAlignmentY(0.0F);
        fEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        fEmail.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 205;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 88, 0, 0);
        jPanel1.add(fEmail, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JPasswordField fConfirmaSenha;
    private javax.swing.JFormattedTextField fCpf;
    private javax.swing.JTextField fEmail;
    private javax.swing.JCheckBox fMostraSenha;
    private javax.swing.JTextField fNome;
    private javax.swing.JPasswordField fSenha;
    private javax.swing.JTextField fUsuario;
    private javax.swing.JLabel jLabelTituloCadastro;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelUsuario1;
    private javax.swing.JLabel jLabelUsuario11;
    private javax.swing.JLabel jLabelUsuario18;
    private javax.swing.JLabel jLabelUsuario7;
    private javax.swing.JLabel jLabelUsuario8;
    private javax.swing.JLabel jLabelUsuario9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
