/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemavendas.cadastrosrapidos;

import infra.validadores.Validador;
import infra.validadores.ViewValidator;
import java.awt.event.ActionEvent;
import sistemavendas.controle.CCliente;
import sistemavendas.negocio.NCliente;

/**
 *
 * @author rhuan
 */
public class CRCliente extends CadastroRapido {

    
    /**
     * Creates new form CRCliente
     */
    public CRCliente() {
        initComponents();
        initMasks();
        initActions();
    }
    
    
    public void init() {        
        this.setVisible(true);
    }
    
    
    @Override
    protected final void initMasks() {
        validator = new ViewValidator();
        validator.required(fCodigo);
        validator.required(fNome);
        validator.fieldCpf(fCpf, "", true, "isCpfValid", new Validador(), String.class);
    }
    
    
    @Override
    protected void cadastrar() {
        
        NCliente cliente = new NCliente();
        CCliente controller = new CCliente();
        
        cliente.setCadastroRapido(true);
        cliente.setCodigo(Integer.parseInt(fCodigo.getText()));
        cliente.setNome(fNome.getText());
        cliente.setCpf(fCpf.getText());
        
        try {
            controller.inserir(cliente);
        } catch (Exception e) {
            showException(e);
        }
        
    }
    
    
    @Override
    protected final void initActions () {
        btSalvar.addActionListener((ActionEvent e) -> {
            cadastrar();
        });
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCadCliente = new javax.swing.JPanel();
        jLabelTituloCadastro = new javax.swing.JLabel();
        jLabelUsuario2 = new javax.swing.JLabel();
        fNome = new javax.swing.JTextField();
        fCodigo = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        fCpf = new javax.swing.JFormattedTextField();
        jLabelUsuario3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 246, 250));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(420, 270));

        panelCadCliente.setBackground(new java.awt.Color(245, 246, 250));
        panelCadCliente.setForeground(new java.awt.Color(245, 246, 250));
        panelCadCliente.setAlignmentX(0.0F);
        panelCadCliente.setAlignmentY(0.0F);
        panelCadCliente.setMaximumSize(new java.awt.Dimension(0, 0));

        jLabelTituloCadastro.setFont(new java.awt.Font("Avenir LT Std 35 Light", 1, 16)); // NOI18N
        jLabelTituloCadastro.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTituloCadastro.setText("Cadastro de Cliente ");
        jLabelTituloCadastro.setAlignmentY(0.0F);

        jLabelUsuario2.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 12)); // NOI18N
        jLabelUsuario2.setForeground(new java.awt.Color(153, 153, 153));
        jLabelUsuario2.setText("Nome");

        fNome.setBackground(new java.awt.Color(245, 246, 250));
        fNome.setAlignmentX(0.0F);
        fNome.setAlignmentY(0.0F);
        fNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        fNome.setMinimumSize(new java.awt.Dimension(400, 20));
        fNome.setName(""); // NOI18N
        fNome.setPreferredSize(new java.awt.Dimension(400, 20));

        fCodigo.setBackground(new java.awt.Color(245, 246, 250));
        fCodigo.setAlignmentX(0.0F);
        fCodigo.setAlignmentY(0.0F);
        fCodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        jLabelDescricao.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 12)); // NOI18N
        jLabelDescricao.setForeground(new java.awt.Color(153, 153, 153));
        jLabelDescricao.setText("Código");

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/30x30/salvar2.png"))); // NOI18N
        btSalvar.setToolTipText("Salvar Registro");
        btSalvar.setAlignmentY(0.0F);
        btSalvar.setMaximumSize(new java.awt.Dimension(80, 39));
        btSalvar.setMinimumSize(new java.awt.Dimension(80, 39));
        btSalvar.setOpaque(false);
        btSalvar.setPreferredSize(new java.awt.Dimension(80, 39));

        fCpf.setBackground(new java.awt.Color(245, 246, 250));
        fCpf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        fCpf.setToolTipText("");
        fCpf.setMinimumSize(new java.awt.Dimension(100, 20));
        fCpf.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabelUsuario3.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 12)); // NOI18N
        jLabelUsuario3.setForeground(new java.awt.Color(153, 153, 153));
        jLabelUsuario3.setText("CPF");

        javax.swing.GroupLayout panelCadClienteLayout = new javax.swing.GroupLayout(panelCadCliente);
        panelCadCliente.setLayout(panelCadClienteLayout);
        panelCadClienteLayout.setHorizontalGroup(
            panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadClienteLayout.createSequentialGroup()
                .addGroup(panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadClienteLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabelTituloCadastro))
                    .addGroup(panelCadClienteLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadClienteLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(fCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadClienteLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabelUsuario2))
                    .addGroup(panelCadClienteLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUsuario3)
                            .addComponent(fNome, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCadClienteLayout.createSequentialGroup()
                                .addComponent(fCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
        );
        panelCadClienteLayout.setVerticalGroup(
            panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadClienteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelTituloCadastro)
                .addGap(24, 24, 24)
                .addComponent(jLabelDescricao)
                .addGap(6, 6, 6)
                .addComponent(fCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelUsuario2)
                .addGap(6, 6, 6)
                .addComponent(fNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelUsuario3)
                .addGroup(panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadClienteLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(fCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelCadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCadCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCadCliente.getAccessibleContext().setAccessibleParent(this);

        getAccessibleContext().setAccessibleName("view_clientes");
        getAccessibleContext().setAccessibleDescription("view_clientes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField fCodigo;
    private javax.swing.JFormattedTextField fCpf;
    private javax.swing.JTextField fNome;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelTituloCadastro;
    private javax.swing.JLabel jLabelUsuario2;
    private javax.swing.JLabel jLabelUsuario3;
    private javax.swing.JPanel panelCadCliente;
    // End of variables declaration//GEN-END:variables

}
