/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemavendas.cadastrosrapidos;

import infra.comunicacao.Sucess;
import infra.validadores.ViewValidator;
import java.awt.event.ActionEvent;
import sistemavendas.controle.CGrupo;
import sistemavendas.negocio.NGrupo;

/**
 *
 * @author rhuan
 */
public class CRGrupo extends CadastroRapido {

    
    private NGrupo grupo;
    
    /**
     * Creates new form CRGrupo
     */
    public CRGrupo() {
        initComponents();
        initMasks();
        initActions();
    }
    
    
    public void init() {
        this.setVisible(true);
    }
    
    
    @Override
    protected final void initMasks() {
        validator = new ViewValidator();
        validator.required(fCodigo);
        validator.required(fDescricao);
    }
    
    
    @Override
    protected void cadastrar() {
        
        NGrupo grupo = new NGrupo();
        CGrupo controller = new CGrupo();
        
        
        grupo.setCodigo(Integer.parseInt(fCodigo.getText()));
        grupo.setDescricao(fDescricao.getText());
        
        try {
            controller.inserir(grupo);
            this.grupo = grupo;
            new Sucess("Grupo cadastrado com sucesso!", "Cadastro Rápido de Grupo").show();
        } catch (Exception e) {
            showException(e);
        }
    }
    
    
    @Override
    protected final void initActions () {
        btSalvar.addActionListener((ActionEvent e) -> {
            cadastrar();
        });
    }

    public NGrupo getGrupo() {
        return grupo;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelCadCliente = new javax.swing.JPanel();
        jLabelTituloCadastro = new javax.swing.JLabel();
        jLabelUsuario2 = new javax.swing.JLabel();
        fDescricao = new javax.swing.JTextField();
        fCodigo = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 246, 250));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(420, 270));

        panelCadCliente.setBackground(new java.awt.Color(245, 246, 250));
        panelCadCliente.setForeground(new java.awt.Color(245, 246, 250));
        panelCadCliente.setAlignmentX(0.0F);
        panelCadCliente.setAlignmentY(0.0F);
        panelCadCliente.setMaximumSize(new java.awt.Dimension(0, 0));
        panelCadCliente.setLayout(new java.awt.GridBagLayout());

        jLabelTituloCadastro.setFont(new java.awt.Font("Avenir LT Std 35 Light", 1, 16)); // NOI18N
        jLabelTituloCadastro.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTituloCadastro.setText("Cadastro de Grupo ");
        jLabelTituloCadastro.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 0);
        panelCadCliente.add(jLabelTituloCadastro, gridBagConstraints);

        jLabelUsuario2.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 12)); // NOI18N
        jLabelUsuario2.setForeground(new java.awt.Color(153, 153, 153));
        jLabelUsuario2.setText("Descriçao");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 38, 0, 0);
        panelCadCliente.add(jLabelUsuario2, gridBagConstraints);

        fDescricao.setBackground(new java.awt.Color(245, 246, 250));
        fDescricao.setAlignmentX(0.0F);
        fDescricao.setAlignmentY(0.0F);
        fDescricao.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        fDescricao.setMinimumSize(new java.awt.Dimension(400, 20));
        fDescricao.setName(""); // NOI18N
        fDescricao.setPreferredSize(new java.awt.Dimension(400, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = -100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 38, 0, 70);
        panelCadCliente.add(fDescricao, gridBagConstraints);

        fCodigo.setBackground(new java.awt.Color(245, 246, 250));
        fCodigo.setAlignmentX(0.0F);
        fCodigo.setAlignmentY(0.0F);
        fCodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 38, 0, 0);
        panelCadCliente.add(fCodigo, gridBagConstraints);

        jLabelDescricao.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 12)); // NOI18N
        jLabelDescricao.setForeground(new java.awt.Color(153, 153, 153));
        jLabelDescricao.setText("Código");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 38, 0, 0);
        panelCadCliente.add(jLabelDescricao, gridBagConstraints);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/30x30/salvar2.png"))); // NOI18N
        btSalvar.setToolTipText("Salvar Registro");
        btSalvar.setAlignmentY(0.0F);
        btSalvar.setMaximumSize(new java.awt.Dimension(80, 39));
        btSalvar.setMinimumSize(new java.awt.Dimension(80, 39));
        btSalvar.setOpaque(false);
        btSalvar.setPreferredSize(new java.awt.Dimension(80, 39));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 110, 21, 70);
        panelCadCliente.add(btSalvar, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelCadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelCadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCadCliente.getAccessibleContext().setAccessibleParent(this);

        getAccessibleContext().setAccessibleName("view_clientes");
        getAccessibleContext().setAccessibleDescription("view_clientes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField fCodigo;
    private javax.swing.JTextField fDescricao;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelTituloCadastro;
    private javax.swing.JLabel jLabelUsuario2;
    private javax.swing.JPanel panelCadCliente;
    // End of variables declaration//GEN-END:variables

}
