SET SQL_MODE =  NO_AUTO_VALUE_ON_ZERO ;
SET TIME_ZONE =  +00:00 ;
--SET autocommit=0;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES UTF8 */;

--
-- DATABASE:  SISVENDASSIMPLES
--


DROP DATABASE SISVENDASSIMPLES;
CREATE DATABASE SISVENDASSIMPLES;
USE SISVENDASSIMPLES;


-- --------------------------------------------------------
--
-- ESTRUTURA DA TABELA  CLIENTES 
--
CREATE TABLE IF NOT EXISTS  CLIENTE  (
   ID INT(11) NOT NULL AUTO_INCREMENT,
   CODIGO INT(10) DEFAULT NULL,
   NOME  VARCHAR(255)  DEFAULT NULL,
   ENDERECO  VARCHAR(255)  DEFAULT NULL,
   BAIRRO  VARCHAR(60)  DEFAULT NULL,
   CIDADE  VARCHAR(60)  DEFAULT NULL,
   UF  VARCHAR(2)  DEFAULT NULL,
   CEP  VARCHAR(15)  DEFAULT NULL,
   TELEFONE  VARCHAR(20)  DEFAULT NULL,
   CELULAR  VARCHAR(20)  DEFAULT NULL,
   ATIVO  TINYINT(1)  DEFAULT NULL,
   SEXO  VARCHAR(12)  DEFAULT NULL,
   EMAIL  VARCHAR(30)  DEFAULT NULL,
   CPF  VARCHAR(20)  DEFAULT NULL,
   RG  VARCHAR(10)  DEFAULT NULL,
   DT_NASCIMENTO  DATE,
   PRIMARY KEY ( ID ),
   UNIQUE KEY (CODIGO)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1 ;


-- --------------------------------------------------------
--
-- ESTRUTURA DA TABELA  FORNECEDORES 
--
CREATE TABLE IF NOT EXISTS  FORNECEDOR  (
   ID INT(11) NOT NULL AUTO_INCREMENT,
   CODIGO INT(10) DEFAULT NULL,
   NOME  VARCHAR(255)  DEFAULT NULL,
   ENDERECO  VARCHAR(255)  DEFAULT NULL,
   BAIRRO  VARCHAR(60)  DEFAULT NULL,
   CIDADE  VARCHAR(60)  DEFAULT NULL,
   UF  VARCHAR(2)  DEFAULT NULL,
   CEP  VARCHAR(15)  DEFAULT NULL,
   TELEFONE  VARCHAR(20)  DEFAULT NULL,
   CELULAR  VARCHAR(20)  DEFAULT NULL,   
   EMAIL  VARCHAR(30)  DEFAULT NULL,
   CNPJ  VARCHAR(20)  DEFAULT NULL,
   ATIVO  TINYINT(1)  DEFAULT NULL,
  PRIMARY KEY ( ID ),
  UNIQUE KEY (CODIGO)

) ENGINE=INNODB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1 ;



-- --------------------------------------------------------
--
-- ESTRUTURA DA TABELA  EMPRESA 
--
CREATE TABLE EMPRESA (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    CODIGO INT(10) DEFAULT NULL,
    RAZAO_SOCIAL  VARCHAR(255)  DEFAULT NULL,
    NOME_FANTASIA VARCHAR(255)  DEFAULT NULL,
    PRODUTOR_RURAL TINYINT(1)  DEFAULT NULL,
    INSCRICAO_ESTADUAL INT(11) DEFAULT NULL,
    INSCRICAO_MUNICIPAL INT(11) DEFAULT NULL,
    CNPJ  VARCHAR(20)  DEFAULT NULL,
    CPF  VARCHAR(20)  DEFAULT NULL,
    MUNICIPIO  VARCHAR(255)  DEFAULT NULL,
    IBGE VARCHAR(15)  DEFAULT NULL,
    BAIRRO  VARCHAR(60)  DEFAULT NULL,
    CIDADE  VARCHAR(60)  DEFAULT NULL,
    LOGRADOURO VARCHAR(60)  DEFAULT NULL,
    UF  VARCHAR(2)  DEFAULT NULL,
    NUMERO INT(10) DEFAULT NULL,
    CEP  VARCHAR(15)  DEFAULT NULL,
    CRT  VARCHAR(60)  DEFAULT NULL,
    TELEFONE  VARCHAR(20)  DEFAULT NULL,
    CELULAR  VARCHAR(20)  DEFAULT NULL,   
    EMAIL  VARCHAR(30)  DEFAULT NULL,
    CERTIFICADO VARCHAR(255)  DEFAULT NULL,
    SENHA VARCHAR(255)  DEFAULT NULL,
    LOGOMARCA VARCHAR(255)  DEFAULT NULL,
    PRIMARY KEY ( ID ),
    UNIQUE KEY (CODIGO)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1 ;


-- --------------------------------------------------------
--
-- ESTRUTURA DA TABELA  PRODUTO 
--
CREATE TABLE IF NOT EXISTS  PRODUTO  (
   ID  INT(11) NOT NULL AUTO_INCREMENT,
   CODIGO INT(10) DEFAULT NULL,
   CODIGO_BARRAS CHAR(20) DEFAULT NULL,
   ID_FORNECEDOR  INT(11) NOT NULL,
   ID_GRUPO INT(11) DEFAULT NULL,
   NOME  VARCHAR(255)  DEFAULT NULL,
   VALOR_CUSTO  DOUBLE DEFAULT NULL,
   VALOR_VENDA  DOUBLE DEFAULT NULL,
   VALOR_LUCRO  DOUBLE DEFAULT NULL,
   PERCENT_LUCRO  DOUBLE DEFAULT NULL,
   QTD_ESTOQUE  INT(11),
   QTD_ESTOQUE_MIN  INT(11),
   QTD_ESTOQUE_MAX  INT(11),
   LOCALIZACAO  VARCHAR(255)  DEFAULT NULL,
   ATIVO  TINYINT(1)  DEFAULT NULL,
   SRC_IMG VARCHAR(500) DEFAULT NULL,
   ID_UNIDADE_MEDIDA_COMERCIAL INT(10) NOT NULL,
   PRIMARY KEY ( ID ),
   UNIQUE KEY (CODIGO),
   KEY  FK_PRODUTO  ( ID_FORNECEDOR ),
   KEY  FK_GRUPO (ID_GRUPO),
   KEY  FK_UNIDADE_MEDIDA_COMERCIAL (ID_UNIDADE_MEDIDA_COMERCIAL)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1 ;


-- --------------------------------------------------------
--
-- ESTRUTURA DA TABELA  GRUPO 
--
CREATE TABLE IF NOT EXISTS GRUPO (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    CODIGO INT(11) NOT NULL,
    DESCRICAO VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID),
    UNIQUE KEY(CODIGO)
);

INSERT INTO GRUPO (CODIGO, DESCRICAO) VALUES (1, 'Alimentos');
INSERT INTO GRUPO (CODIGO, DESCRICAO) VALUES (2, 'Bebidas');
INSERT INTO GRUPO (CODIGO, DESCRICAO) VALUES (3, 'Cama, Mesa e Banho');
INSERT INTO GRUPO (CODIGO, DESCRICAO) VALUES (4, 'Diversos');
INSERT INTO GRUPO (CODIGO, DESCRICAO) VALUES (5, 'Eletrodomésticos');
INSERT INTO GRUPO (CODIGO, DESCRICAO) VALUES (6, 'Eletrônicos');
INSERT INTO GRUPO (CODIGO, DESCRICAO) VALUES (7, 'Informática');
INSERT INTO GRUPO (CODIGO, DESCRICAO) VALUES (8, 'Móveis e Decoração');
INSERT INTO GRUPO (CODIGO, DESCRICAO) VALUES (9, 'Telefonia');




CREATE TABLE IF NOT EXISTS UNIDADE_MEDIDA_COMERCIAL (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    CODIGO INT(11) NOT NULL,
    UNIDADE VARCHAR(25) NOT NULL,
    DESCRICAO VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID),
    UNIQUE KEY(CODIGO)
);

INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (1, "AMPOLA", "AMPOLA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (2, "BALDE", "BALDE");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (3, "BANDEJ", "BANDEJA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (4, "BARRA", "BARRA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (5, "BISNAG", "BISNAGA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (6, "BLOCO", "BLOCO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (7, "BOBINA", "BOBINA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (8, "BOMB", "BOMBONA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (9, "CAPS", "CAPSULA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (10, "CART", "CARTELA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (11, "CENTO", "CENTO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (12, "CJ", "CONJUNTO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (13, "CM", "CENTIMETRO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (14, "CM2", "CENTIMETRO QUADRADO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (15, "CX", "CAIXA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (16, "CX2", "CAIXA COM 2 UNIDADES");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (17, "CX3", "CAIXA COM 3 UNIDADES");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (18, "CX5", "CAIXA COM 5 UNIDADES");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (19, "CX10", "CAIXA COM 10 UNIDADES");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (20, "CX15", "CAIXA COM 15 UNIDADES");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (21, "CX20", "CAIXA COM 20 UNIDADES");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (22, "CX25", "CAIXA COM 25 UNIDADES");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (23, "CX50", "CAIXA COM 50 UNIDADES");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (24, "CX100", "CAIXA COM 100 UNIDADES");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (25, "DISP", "DISPLAY");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (26, "DUZIA", "DUZIA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (27, "EMBAL", "EMBALAGEM");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (28, "FARDO", "FARDO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (29, "FOLHA", "FOLHA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (30, "FRASCO", "FRASCO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (31, "GALAO", "GALÃO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (32, "GF", "GARRAFA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (33, "GRAMAS", "GRAMAS");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (34, "JOGO", "JOGO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (35, "KG", "QUILOGRAMA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (36, "KIT", "KIT");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (37, "LATA", "LATA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (38, "LITRO", "LITRO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (39, "M", "METRO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (40, "M2", "METRO QUADRADO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (41, "M3", "METRO CÚBICO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (42, "MILHEI", "MILHEIRO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (43, "ML", "MILILITRO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (44, "MWH", "MEGAWATT HORA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (45, "PACOTE", "PACOTE");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (46, "PALETE", "PALETE");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (47, "PARES", "PARES");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (48, "PC", "PEÇA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (49, "POTE", "POTE");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (50, "K", "QUILATE");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (51, "RESMA", "RESMA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (52, "ROLO", "ROLO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (53, "SACO", "SACO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (54, "SACOLA", "SACOLA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (55, "TAMBOR", "TAMBOR");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (56, "TANQUE", "TANQUE");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (57, "TON", "TONELADA");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (58, "TUBO", "TUBO");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (59, "UNID", "UNIDADE");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (60, "VASIL", "VASILHAME");
INSERT INTO UNIDADE_MEDIDA_COMERCIAL (CODIGO, UNIDADE, DESCRICAO) VALUES (61, "VIDRO", "VIDRO");


-- --------------------------------------------------------
--
-- ESTRUTURA DA TABELA  USUARIO 
--
CREATE TABLE IF NOT EXISTS  USUARIO  (
   ID INT(11) NOT NULL AUTO_INCREMENT,
   CODIGO INT(10) DEFAULT NULL,
   ATIVO  TINYINT(1)  DEFAULT NULL,
   ADMINISTRADOR  TINYINT(1)  DEFAULT NULL,
   CPF  VARCHAR(20)  DEFAULT NULL,
   USUARIO  VARCHAR(255)  NOT NULL,
   SENHA  VARCHAR(40)  NOT NULL,
   NOME  VARCHAR(255)  NOT NULL,
   EMAIL  VARCHAR(30)  DEFAULT NULL,
   PRIMARY KEY ( ID ),
   UNIQUE KEY (CODIGO),
   UNIQUE KEY (USUARIO)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1 ;



-- --------------------------------------------------------
--
-- ESTRUTURA DA TABELA  VENDAS 
--
CREATE TABLE IF NOT EXISTS  VENDA  (
   ID INT(11) NOT NULL AUTO_INCREMENT,
   CODIGO INT(10) DEFAULT NULL,   
   DATA_VENDA  DATE DEFAULT NULL,   
   DESCONTO_PERCENT  FLOAT DEFAULT NULL,
   DESCONTO_VALOR FLOAT DEFAULT NULL,
   TOTAL_PAGO  FLOAT DEFAULT NULL,
   SUB_TOTAL  FLOAT DEFAULT NULL,
   VALOR_TOTAL  FLOAT DEFAULT NULL,  
   ID_CLIENTE  INT(11) NOT NULL,   
  PRIMARY KEY ( ID ),
  UNIQUE KEY (CODIGO),
  KEY  FK_VENDAS_1  ( ID_CLIENTE )
) ENGINE=INNODB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1 ;



-- --------------------------------------------------------
--
-- ESTRUTURA DA TABELA  CARRINHO 
--
CREATE TABLE IF NOT EXISTS  CARRINHO  (
   ID INT(11) NOT NULL AUTO_INCREMENT,
   DESCRICAO  VARCHAR(255) DEFAULT NULL,
   ID_VENDA  INT(11) NOT NULL,
  PRIMARY KEY ( ID ),
  KEY  FK_CARRINHO_ID_VENDA  ( ID_VENDA )
) ENGINE=INNODB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1 ;


-- --------------------------------------------------------
--
-- ESTRUTURA DA TABELA  CARRINHO_PRODUTO 
--
CREATE TABLE IF NOT EXISTS  CARRINHO_PRODUTO  (
   ID  INT(11) NOT NULL AUTO_INCREMENT,
   ID_PRODUTO  INT(11) DEFAULT NULL,
   QUANTIDADE  DOUBLE DEFAULT 0,
   ID_CARRINHO INT(11) DEFAULT NULL,
  PRIMARY KEY ( ID ),
  KEY  FK_CARRINHO_PRODUTO_ID_PRODUTO   ( ID_PRODUTO  ),
  KEY  FK_CARRINHO_PRODUTO_ID_CARRINHO  ( ID_CARRINHO )
) ENGINE=INNODB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1 ;



-- --------------------------------------------------------
--
-- ESTRUTURA DA TABELA  FORMA_PAGAMENTO 
--
CREATE TABLE IF NOT EXISTS FORMA_PAGAMENTO (
    ID INT(11) NOT NULL AUTO_INCREMENT,    
    DESCRICAO VARCHAR(50) NOT NULL,
    ENTRADA INT(11),
    PARCELAS INT(11),
    ID_VENDA INT(11),
    PRIMARY KEY(ID),
    KEY  FK_FORMA_PAGAMENTO_ID_VENDA   ( ID_VENDA  )
);


-- --------------------------------------------------------
--
-- ESTRUTURA DA TABELA  PRODUTO_CODIGO_BARRAS 
--
CREATE TABLE IF NOT EXISTS  PRODUTO_CODIGO_BARRAS  (
   ID  INT(11) NOT NULL AUTO_INCREMENT,
   ID_PRODUTO  INT(11) DEFAULT NULL,
   CODIGO_BARRAS  VARCHAR(30) DEFAULT NULL,
  PRIMARY KEY ( ID ),
  KEY  FK_PRODUTO_CODIGO_BARRAS_ID_PRODUTO   ( ID_PRODUTO  )
) ENGINE=INNODB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1 ;



--
-- CONSTRAINTS FOR DUMPED TABLES
--

--
-- LIMITADORES PARA A TABELA  PRODUTOS 
--

-- PRODUTO -> FORNECEDOR
ALTER TABLE  PRODUTO 
  ADD CONSTRAINT  FK_PRODUTOS_FORNECEDOR  FOREIGN KEY ( ID_FORNECEDOR ) REFERENCES  FORNECEDOR  ( ID );
-- PRODUTO -> UNIDADE_MEDIDA_COMERCIAL
ALTER TABLE  PRODUTO 
  ADD CONSTRAINT  FK_PRODUTOS_UNIDADE_MEDIDA_COMERCIAL  FOREIGN KEY ( ID_UNIDADE_MEDIDA_COMERCIAL) REFERENCES  UNIDADE_MEDIDA_COMERCIAL ( ID );
-- PRODUTO -> FORMA PAGAMENTO
ALTER TABLE  PRODUTO 
  ADD CONSTRAINT  FK_PRODUTOS_GRUPO  FOREIGN KEY ( ID_GRUPO ) REFERENCES  GRUPO  ( ID );
-- FORMA PAGAMENTO -> VENDA
ALTER TABLE  FORMA_PAGAMENTO 
  ADD CONSTRAINT  FK_FORMA_PAGAMENTO_ID_VENDA  FOREIGN KEY ( ID_VENDA ) REFERENCES  VENDA  ( ID );
-- VENDA -> CLIENTE
ALTER TABLE  VENDA 
  ADD CONSTRAINT  FK_VENDA_CLIENTE  FOREIGN KEY ( ID_CLIENTE ) REFERENCES  CLIENTE  ( ID );
-- CARRINHO PRODUTO => PRODUTO/CARRINHO
ALTER TABLE  CARRINHO_PRODUTO 
  ADD CONSTRAINT  FK_CARRINHO_PRODUTO_ID_PRODUTO  FOREIGN KEY ( ID_PRODUTO ) REFERENCES  PRODUTO  ( ID ),
  ADD CONSTRAINT  FK_CARRINHO_PRODUTO_ID_CARRINHO  FOREIGN KEY ( ID_CARRINHO ) REFERENCES  CARRINHO  ( ID ) ON DELETE CASCADE ON UPDATE CASCADE;




CREATE TABLE OPERACAO (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    CS_OPERACAO VARCHAR (20),
    PRIMARY KEY (ID)
);


CREATE TABLE PROGRAMA (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CS_TIPO VARCHAR(45) NOT NULL,    
    PRIMARY KEY (ID)    
);

CREATE TABLE PROGRAMA_OPERACAO (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    ID_PROGRAMA INT(11) NOT NULL,
    ID_OPERACAO INT(11) NOT NULL,
    ID_USUARIO  INT(11) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE  PROGRAMA_OPERACAO 
  ADD CONSTRAINT  FK_PROGRAMA_OPERACAO_ID_PROGRAMA  FOREIGN KEY ( ID_PROGRAMA ) REFERENCES  PROGRAMA  ( ID );
  ADD CONSTRAINT  FK_PROGRAMA_OPERACAO_ID_OPERACAO  FOREIGN KEY ( ID_OPERACAO ) REFERENCES  OPERACAO  ( ID );
  ADD CONSTRAINT  FK_PROGRAMA_OPERACAO_ID_USUARIO   FOREIGN KEY ( ID_USUARIO )  REFERENCES  USUARIO   ( ID );


INSERT INTO OPERACAO (CS_OPERACAO) VALUES ('INCLUIR');
INSERT INTO OPERACAO (CS_OPERACAO) VALUES ('ALTERAR');
INSERT INTO OPERACAO (CS_OPERACAO) VALUES ('EXCLUIR');
INSERT INTO OPERACAO (CS_OPERACAO) VALUES ('PESQUISAR');
INSERT INTO OPERACAO (CS_OPERACAO) VALUES ('GERAR_RELATORIO');
INSERT INTO OPERACAO (CS_OPERACAO) VALUES ('VISUALIZACAO');


INSERT INTO PROGRAMA (NOME, CS_TIPO) VALUES ('Cadastro de Cliente', 'Cadastro');
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (1, 1, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (1, 2, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (1, 3, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (1, 4, 1);


INSERT INTO PROGRAMA (NOME, CS_TIPO) VALUES ('Cadastro de Fornecedor', 'Cadastro');
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (2, 1, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (2, 2, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (2, 3, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (2, 4, 1);


INSERT INTO PROGRAMA (NOME, CS_TIPO) VALUES ('Cadastro de Grupo', 'Cadastro');
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (3, 1, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (3, 2, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (3, 3, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (3, 4, 1);


INSERT INTO PROGRAMA (NOME, CS_TIPO) VALUES ('Cadastro de Produto', 'Cadastro');
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (4, 1, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (4, 2, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (4, 3, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (4, 4, 1);


INSERT INTO PROGRAMA (NOME, CS_TIPO) VALUES ('Cadastro de Usuario', 'Cadastro');
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (5, 1, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (5, 2, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (5, 3, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (5, 4, 1);


INSERT INTO PROGRAMA (NOME, CS_TIPO) VALUES ('Realizar Venda', 'Cadastro');
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (6, 1, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (6, 2, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (6, 3, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (6, 4, 1);


INSERT INTO PROGRAMA (NOME, CS_TIPO) VALUES ('Cadastro de Empresa', 'Cadastro');
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (7, 1, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (7, 2, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (7, 3, 1);
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (7, 4, 1);


INSERT INTO PROGRAMA (NOME, CS_TIPO) VALUES ('Dashboard', 'Visualizacao');
INSERT INTO PROGRAMA_OPERACAO (ID_PROGRAMA, ID_OPERACAO, ID_USUARIO) VALUES (8, 6, 1);


CREATE TABLE CODIGOS_UF (
   ID INT(11) NOT NULL AUTO_INCREMENT,
   CODIGO_IBGE INT(5) DEFAULT NULL,
   ESTADO VARCHAR(60)  DEFAULT NULL,
   SIGLA VARCHAR(3)  DEFAULT NULL,
   PRIMARY KEY ( ID ),
   UNIQUE KEY (CODIGO_IBGE)
);



INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (11,  'Rondônia', 'RO');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (12,  'Acre', 'AC');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (13,  'Amazonas', 'AM');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (14,  'Roraima', 'RR');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (15,  'Pará', 'PA');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (16,  'Amapá', 'AP');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (17,  'Tocantins', 'TO');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (21,  'Maranhão', 'MA');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (22,  'Piauí', 'PI');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (23,  'Ceará', 'CE');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (24,  'Rio Grande do Norte', 'RN');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (25,  'Paraíba', 'PB');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (26,  'Pernambuco', 'PE');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (27,  'Alagoas', 'AL');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (28,  'Sergipe', 'SE');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (29,  'Bahia', 'BA');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (31,  'Minas Gerais', 'MG');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (32,  'Espírito Santo' , 'ES');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (33,  'Rio de Janeiro', 'RJ');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (35,  'São Paulo', 'SP');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (41,  'Paraná', 'PR');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (42,  'Santa Catarina' , 'SC');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (43,  'Rio Grande do Sul' , 'RS');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (50,  'Mato Grosso do Sul' , 'MS');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (51,  'Mato Grosso' , 'MT');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (52,  'Goiás', 'GO');
INSERT INTO CODIGOS_UF(CODIGO_IBGE, ESTADO, SIGLA) VALUES (53,  'Distrito Federal' , 'DF');


CREATE TABLE SISTEMA_CONFIG (
   ID INT(11) NOT NULL AUTO_INCREMENT,
   EMAIL VARCHAR(60)  DEFAULT NULL,
   SENHA VARCHAR(30)  DEFAULT NULL,
   PRIMARY KEY ( ID )
);
